swagger: '2.0'
info:
  title: Hello World Portal
  version: "1"
  description: A simple portal for a hello-world proxy
host: {environment_group_hostname}
basePath:
  /hello-world
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://{environment_group_hostname}/v1/oauth20/authorize
    tokenUrl: https://{environment_group_hostname}/v1/oauth20/token
    scopes:
      openid: Open ID info
      email: Email info
      profile: Profile info
security:
  - OAuth2: [openid, email, profile]
paths:
  /:
    get:
      operationId: GetMessage
      responses:
        '200':
          description: A successful response.